version: '3.9'

services:
  app:
    container_name: go-bank-api
    build: 
      context: .
    ports:
      - "8084:8084"
    depends_on:
      - db
  
  db:
    image: postgres:latest
    container_name: go-bank-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=go_bank_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data:

